/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 339e6a3b-6c5c-4cde-83de-500619778cbc

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.

-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Classical


variable {V : Type*} [Fintype V] [DecidableEq V]

-- ══════════════════════════════════════════════════════════════════════════════
-- DEFINITIONS
-- ══════════════════════════════════════════════════════════════════════════════

def isTrianglePacking (G : SimpleGraph V) [DecidableRel G.Adj] (S : Finset (Finset V)) : Prop :=
  S ⊆ G.cliqueFinset 3 ∧
  Set.Pairwise (S : Set (Finset V)) (fun t1 t2 => (t1 ∩ t2).card ≤ 1)

noncomputable def trianglePackingNumber (G : SimpleGraph V) [DecidableRel G.Adj] : ℕ :=
  (G.cliqueFinset 3).powerset.filter (isTrianglePacking G) |>.image Finset.card |>.max |>.getD 0

def isMaxPacking (G : SimpleGraph V) [DecidableRel G.Adj] (M : Finset (Finset V)) : Prop :=
  isTrianglePacking G M ∧ M.card = trianglePackingNumber G

/-- Triangle covering number: minimum edges to hit all triangles -/
noncomputable def triangleCoveringNumber (G : SimpleGraph V) [DecidableRel G.Adj] : ℕ :=
  sInf { n | ∃ E : Finset (Sym2 V), E.card = n ∧ E ⊆ G.edgeFinset ∧
    ∀ t ∈ G.cliqueFinset 3, ∃ e ∈ E, e ∈ t.sym2 }

/-- M-edges incident to vertex v -/
def M_edges_at (M : Finset (Finset V)) (v : V) : Finset (Sym2 V) :=
  M.biUnion (fun X => X.sym2.filter (fun e => v ∈ e))

/-- Triangles that share an M-edge containing v -/
def trianglesSharingMEdgeAt (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (v : V) : Finset (Finset V) :=
  (G.cliqueFinset 3).filter (fun t => ∃ e ∈ M_edges_at M v, e ∈ t.sym2)

def externalTrianglesAt (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (v : V) : Finset (Finset V) :=
  trianglesSharingMEdgeAt G M v \ M

structure Cycle4 (G : SimpleGraph V) [DecidableRel G.Adj] (M : Finset (Finset V)) where
  A : Finset V
  B : Finset V
  C : Finset V
  D : Finset V
  hA : A ∈ M
  hB : B ∈ M
  hC : C ∈ M
  hD : D ∈ M
  hM_eq : M = {A, B, C, D}
  v_ab : V
  v_bc : V
  v_cd : V
  v_da : V
  hAB : A ∩ B = {v_ab}
  hBC : B ∩ C = {v_bc}
  hCD : C ∩ D = {v_cd}
  hDA : D ∩ A = {v_da}
  h_vab_A : v_ab ∈ A
  h_vab_B : v_ab ∈ B
  h_vbc_B : v_bc ∈ B
  h_vbc_C : v_bc ∈ C
  h_vcd_C : v_cd ∈ C
  h_vcd_D : v_cd ∈ D
  h_vda_D : v_da ∈ D
  h_vda_A : v_da ∈ A
  h_diag_AC : (A ∩ C).card ≤ 1
  h_diag_BD : (B ∩ D).card ≤ 1
  h_vab_ne_vbc : v_ab ≠ v_bc
  h_vbc_ne_vcd : v_bc ≠ v_cd
  h_vcd_ne_vda : v_cd ≠ v_da
  h_vda_ne_vab : v_da ≠ v_ab

variable (cycle4_all_triangles_contain_shared : ∀ (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (hM : isMaxPacking G M) (cfg : Cycle4 G M)
    (t : Finset V) (ht : t ∈ G.cliqueFinset 3),
    cfg.v_ab ∈ t ∨ cfg.v_bc ∈ t ∨ cfg.v_cd ∈ t ∨ cfg.v_da ∈ t)

variable (external_share_common_vertex : ∀ (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (hM : isMaxPacking G M) (cfg : Cycle4 G M)
    (v : V) (h_shared : v = cfg.v_ab ∨ v = cfg.v_bc ∨ v = cfg.v_cd ∨ v = cfg.v_da),
    ∃ x : V, x ≠ v ∧ ∀ t ∈ externalTrianglesAt G M v, x ∈ t)

variable {G : SimpleGraph V} [DecidableRel G.Adj] {M : Finset (Finset V)}

/-- The 4 edges covering M-elements -/
def M_cover_edges (cfg : Cycle4 G M) : Finset (Sym2 V) :=
  {s(cfg.v_ab, cfg.v_da), s(cfg.v_ab, cfg.v_bc), s(cfg.v_bc, cfg.v_cd), s(cfg.v_cd, cfg.v_da)}

#check external_share_common_vertex

/-- Get external vertex for each shared vertex -/
noncomputable def get_x_ab (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (hM : isMaxPacking G M) (cfg : Cycle4 G M) : V :=
  (external_share_common_vertex G M hM cfg cfg.v_ab (Or.inl rfl)).choose

noncomputable def get_x_bc (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (hM : isMaxPacking G M) (cfg : Cycle4 G M) : V :=
  (external_share_common_vertex G M hM cfg cfg.v_bc (Or.inr (Or.inl rfl))).choose

noncomputable def get_x_cd (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (hM : isMaxPacking G M) (cfg : Cycle4 G M) : V :=
  (external_share_common_vertex G M hM cfg cfg.v_cd (Or.inr (Or.inr (Or.inl rfl)))).choose

noncomputable def get_x_da (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (hM : isMaxPacking G M) (cfg : Cycle4 G M) : V :=
  (external_share_common_vertex G M hM cfg cfg.v_da (Or.inr (Or.inr (Or.inr rfl)))).choose

/-- The 4 edges covering external triangles -/
noncomputable def external_cover_edges (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (hM : isMaxPacking G M) (cfg : Cycle4 G M) : Finset (Sym2 V) :=
  {s(cfg.v_ab, get_x_ab external_share_common_vertex G M hM cfg),
   s(cfg.v_bc, get_x_bc external_share_common_vertex G M hM cfg),
   s(cfg.v_cd, get_x_cd external_share_common_vertex G M hM cfg),
   s(cfg.v_da, get_x_da external_share_common_vertex G M hM cfg)}

/-- The full 8-edge cover -/
noncomputable def full_cover (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (hM : isMaxPacking G M) (cfg : Cycle4 G M) : Finset (Sym2 V) :=
  M_cover_edges cfg ∪ external_cover_edges external_share_common_vertex G M hM cfg

-- ══════════════════════════════════════════════════════════════════════════════
-- HELPER LEMMAS
-- ══════════════════════════════════════════════════════════════════════════════

lemma triangle_card_eq_3 (G : SimpleGraph V) [DecidableRel G.Adj]
    (t : Finset V) (ht : t ∈ G.cliqueFinset 3) : t.card = 3 := by
      -- Since $t$ is in the cliqueFinset 3, by definition, $t$ has exactly 3 elements.
      simp [SimpleGraph.cliqueFinset] at ht;
      -- By definition of IsNClique, the cardinality of t is 3.
      apply ht.card_eq

lemma external_triangle_contains_v (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (v : V) (t : Finset V)
    (ht : t ∈ externalTrianglesAt G M v) : v ∈ t := by
      -- Since $t$ is in $trianglesSharingMEdgeAt G M v$, there exists an edge $e \in M_edges_at M v$ such that $e \in t.sym2$.
      obtain ⟨e, heM, heT⟩ : ∃ e ∈ M_edges_at M v, e ∈ t.sym2 := by
        -- By definition of trianglesSharingMEdgeAt, if t is in externalTrianglesAt G M v, then there exists an edge e in M_edges_at M v such that e is in t.sym2.
        have h_edge : t ∈ trianglesSharingMEdgeAt G M v := by
          exact Finset.mem_sdiff.mp ht |>.1;
        unfold trianglesSharingMEdgeAt at h_edge; aesop;
      unfold M_edges_at at heM; aesop;

#check full_cover

/-- Full cover covers all M-elements -/
lemma full_cover_covers_M (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (hM : isMaxPacking G M) (cfg : Cycle4 G M)
    (X : Finset V) (hX : X ∈ M) :
    ∃ e ∈ full_cover external_share_common_vertex G M hM cfg, e ∈ X.sym2 := by
      -- Split into cases based on which of the four M-elements cfg corresponds to.
      by_cases hX_A : X = cfg.A;
      · refine' ⟨ s(cfg.v_ab, cfg.v_da), _, _ ⟩ <;> simp +decide [ *, full_cover ];
        · exact Or.inl ( Finset.mem_insert_self _ _ );
        · exact ⟨ cfg.h_vab_A, cfg.h_vda_A ⟩;
      · -- Since X is in M and M is {A, B, C, D}, X must be one of these four elements.
        have hX_cases : X = cfg.B ∨ X = cfg.C ∨ X = cfg.D := by
          have := cfg.hM_eq; aesop;
        rcases hX_cases with ( rfl | rfl | rfl ) <;> simp +decide [ *, full_cover, M_cover_edges ];
        · exact Or.inr <| Or.inl ⟨ cfg.h_vab_B, cfg.h_vbc_B ⟩;
        · exact Or.inr <| Or.inr <| Or.inl ⟨ cfg.h_vbc_C, cfg.h_vcd_C ⟩;
        · exact Or.inr <| Or.inr <| Or.inr <| Or.inl ⟨ cfg.h_vcd_D, cfg.h_vda_D ⟩

/-- Full cover covers all external triangles -/
lemma full_cover_covers_external (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (hM : isMaxPacking G M) (cfg : Cycle4 G M)
    (v : V) (h_shared : v = cfg.v_ab ∨ v = cfg.v_bc ∨ v = cfg.v_cd ∨ v = cfg.v_da)
    (t : Finset V) (ht : t ∈ externalTrianglesAt G M v) :
    ∃ e ∈ full_cover external_share_common_vertex G M hM cfg, e ∈ t.sym2 := by
      -- Since $t$ is in the external triangles at $v$, this means that $t$ is covered by one of the edges in the external cover. Therefore, there must be an edge $e$ in the external cover such that $e$ is in $t.sym2$.
      obtain ⟨e, he⟩ : ∃ e ∈ external_cover_edges external_share_common_vertex G M hM cfg, e ∈ t.sym2 := by
        -- Since $x$ is in $t$ and $v$ is in $t$, the edge $(v, x)$ is in $t.sym2$.
        have h_edge_in_t : s(v, (external_share_common_vertex G M hM cfg v h_shared).choose) ∈ t.sym2 := by
          -- Since $x$ is in $t$ by definition of `external_share_common_vertex`, and $v$ is in $t$ because $t$ is in the external triangles at $v$, the pair $(v, x)$ is in $t.sym2$.
          have h_x_in_t : (external_share_common_vertex G M hM cfg v h_shared).choose ∈ t := by
            exact ( external_share_common_vertex G M hM cfg v h_shared |> Exists.choose_spec |> And.right ) t ht;
          simp +decide [ *, Finset.mem_sym2_iff ];
          exact?;
        refine' ⟨ _, _, h_edge_in_t ⟩;
        rcases h_shared with ( rfl | rfl | rfl | rfl ) <;> simp +decide [ external_cover_edges ];
        · exact Or.inl <| Or.inl rfl;
        · exact Or.inr <| Or.inl <| Or.inl rfl;
        · exact Or.inr <| Or.inr <| Or.inl <| Or.inl rfl;
        · exact Or.inr <| Or.inr <| Or.inr <| Or.inl <| rfl;
      exact ⟨ e, Finset.mem_union_right _ he.1, he.2 ⟩

lemma shares_M_edge_of_contains_shared_vertex (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (hM : isMaxPacking G M) (cfg : Cycle4 G M)
    (t : Finset V) (ht : t ∈ G.cliqueFinset 3) (h_not_M : t ∉ M)
    (v : V) (hv : v = cfg.v_ab ∨ v = cfg.v_bc ∨ v = cfg.v_cd ∨ v = cfg.v_da)
    (hvt : v ∈ t) :
    ∃ e ∈ M_edges_at M v, e ∈ t.sym2 := by
      have h_exists_e : ∃ e ∈ M, v ∈ e := by
        rcases hv with ( rfl | rfl | rfl | rfl ) <;> [ exact ⟨ _, cfg.hA, cfg.h_vab_A ⟩ ; exact ⟨ _, cfg.hB, cfg.h_vbc_B ⟩ ; exact ⟨ _, cfg.hC, cfg.h_vcd_C ⟩ ; exact ⟨ _, cfg.hD, cfg.h_vda_D ⟩ ];
      -- Since $v \in t$ and $v \in e$, the edge $\{v, v\}$ is in $t.sym2$.
      obtain ⟨e, heM, hev⟩ := h_exists_e;
      use s(v, v);
      simp [hev, hvt];
      unfold M_edges_at; aesop;

lemma t_in_external_of_not_in_M_and_shared (G : SimpleGraph V) [DecidableRel G.Adj]
    (M : Finset (Finset V)) (hM : isMaxPacking G M) (cfg : Cycle4 G M)
    (t : Finset V) (ht : t ∈ G.cliqueFinset 3) (h_not_M : t ∉ M)
    (v : V) (hv : v = cfg.v_ab ∨ v = cfg.v_bc ∨ v = cfg.v_cd ∨ v = cfg.v_da)
    (hvt : v ∈ t) :
    t ∈ externalTrianglesAt G M v := by
      refine' Finset.mem_sdiff.mpr ⟨ _, _ ⟩;
      · refine' Finset.mem_filter.mpr ⟨ ht, _ ⟩;
        exact?;
      · exact h_not_M