#!/usr/bin/env python3
"""
Search for m such that every cell (k,l) in [0,12)^2 is covered by some
index-1 prime p <= 1000 with p | 2^k * 3^l * m + 1.

A prime p is "index-1" if <2,3> = (Z/pZ)*.
"""

from math import gcd
from functools import reduce

def is_prime(n):
    if n < 2: return False
    if n < 4: return True
    if n % 2 == 0 or n % 3 == 0: return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i+2) == 0: return False
        i += 6
    return True

def subgroup_size_23(p):
    """Size of the subgroup generated by 2 and 3 in (Z/pZ)*."""
    if p <= 3: return 0
    seen = set()
    # BFS/closure approach
    seen.add(1)
    queue = [1]
    while queue:
        x = queue.pop()
        y = (x * 2) % p
        if y not in seen:
            seen.add(y)
            queue.append(y)
        y = (x * 3) % p
        if y not in seen:
            seen.add(y)
            queue.append(y)
    return len(seen)

def is_index1(p):
    """Check if <2,3> = (Z/pZ)*."""
    if p <= 3: return False
    if not is_prime(p): return False
    return subgroup_size_23(p) == p - 1

# Find all index-1 primes <= 1000
print("Finding index-1 primes <= 1000...")
index1_primes = [p for p in range(5, 1001) if is_index1(p)]
print(f"Found {len(index1_primes)} index-1 primes <= 1000")
print(f"First few: {index1_primes[:20]}")
print(f"Last few: {index1_primes[-10:]}")

# For each prime p and each possible residue r mod p,
# compute which cells (k,l) are covered.
# Cell (k,l) is covered by (p, r) iff 2^k * 3^l * r ≡ -1 (mod p)
# i.e., r ≡ -(2^k * 3^l)^{-1} (mod p)
# So for a fixed prime p, all cells with the same value of 2^k*3^l mod p
# are covered by the same choice of r.

GRID = 12

# Precompute cell values
cell_values = {}  # (k,l) -> 2^k * 3^l (as integer, we'll reduce mod p later)
for k in range(GRID):
    for l in range(GRID):
        cell_values[(k,l)] = pow(2, k) * pow(3, l)

# For each prime p, compute the partition of cells by their 2^k*3^l mod p value
# Each partition class can be covered by one choice of r
prime_coversets = {}  # (prime, value_mod_p) -> set of cells
for p in index1_primes:
    groups = {}
    for (k,l), v in cell_values.items():
        vm = v % p
        if vm not in groups:
            groups[vm] = set()
        groups[vm].add((k,l))
    for vm, cells in groups.items():
        prime_coversets[(p, vm)] = cells

print(f"\nTotal cover options: {len(prime_coversets)}")

# Now we need to find a selection: for each selected prime p, choose one value vm,
# such that the union of prime_coversets[(p, vm)] covers all 144 cells.
# Constraint: we can choose at most one vm per prime p.

# This is a set cover problem with the constraint that selections from the same
# prime are mutually exclusive (we can only pick one residue per prime).

# Greedy approach: repeatedly pick the (p, vm) pair that covers the most uncovered cells,
# but once we pick a pair for prime p, remove all other options for p.

all_cells = set((k,l) for k in range(GRID) for l in range(GRID))
uncovered = set(all_cells)
selected = []  # list of (p, vm) pairs
used_primes = set()

# Sort cover sets by size (descending) for efficiency
sorted_options = sorted(prime_coversets.items(), key=lambda x: len(x[1]), reverse=True)

while uncovered:
    best_key = None
    best_new = 0
    for key, cells in sorted_options:
        p = key[0]
        if p in used_primes:
            continue
        new_covered = len(cells & uncovered)
        if new_covered > best_new:
            best_new = new_covered
            best_key = key
    if best_key is None or best_new == 0:
        print(f"\nGreedy stuck! {len(uncovered)} cells uncovered:")
        for cell in sorted(uncovered):
            print(f"  {cell}")
        break
    selected.append(best_key)
    used_primes.add(best_key[0])
    uncovered -= prime_coversets[best_key]
    print(f"Selected prime {best_key[0]}, value {best_key[1]}: covers {best_new} new cells, {len(uncovered)} remaining")

if not uncovered:
    print(f"\n*** SUCCESS! All 144 cells covered with {len(selected)} primes ***")
    
    # Now compute m via CRT
    # For each (p, vm), we need m ≡ -(vm)^{-1} (mod p)
    # i.e., vm * m ≡ -1 (mod p)
    
    def modinv(a, m):
        g, x, _ = extended_gcd(a, m)
        if g != 1:
            raise ValueError(f"No inverse of {a} mod {m}")
        return x % m
    
    def extended_gcd(a, b):
        if a == 0:
            return b, 0, 1
        g, x, y = extended_gcd(b % a, a)
        return g, y - (b // a) * x, x
    
    residues = []
    moduli = []
    for p, vm in selected:
        # m ≡ -(vm)^{-1} (mod p)
        r = (-modinv(vm, p)) % p
        residues.append(r)
        moduli.append(p)
        print(f"  p={p}: m ≡ {r} (mod {p})")
    
    # CRT
    def crt(residues, moduli):
        M = reduce(lambda a, b: a * b, moduli)
        x = 0
        for r, m in zip(residues, moduli):
            Mi = M // m
            yi = modinv(Mi, m)
            x = (x + r * Mi * yi) % M
        return x, M
    
    m, M = crt(residues, moduli)
    print(f"\nm = {m}")
    print(f"M (product of primes) = {M}")
    print(f"m has {len(str(m))} digits")
    
    # Verify
    print("\nVerifying...")
    all_ok = True
    for k in range(GRID):
        for l in range(GRID):
            found = False
            for p, vm in selected:
                val = pow(2, k) * pow(3, l) * m + 1
                if val % p == 0:
                    found = True
                    break
            if not found:
                print(f"  FAIL: cell ({k},{l}) not covered!")
                all_ok = False
    if all_ok:
        print("All cells verified!")
    
    # Print the primes used
    print(f"\nPrimes used: {sorted(p for p, _ in selected)}")
    
    # Print m for Lean
    print(f"\nm for Lean: {m}")
else:
    print(f"\nFailed to cover all cells. {len(uncovered)} remaining.")
