#!/usr/bin/env python3
"""
cayley_search.py — search Cayley graphs of NON-cyclic abelian groups Z_a x Z_b
for an E944 / (4,1)-graph witness. (count, E944)

Circulants = Cayley graphs of cyclic Z_n, now empirically closed (count_circulant_search.md).
The next-natural vertex-transitive family is Cayley graphs of Z_a x Z_b (and
elementary abelian Z_2^k etc.). Vertex-transitivity again makes criticality
constant on connection-set orbits, so we get the same speedup: witness iff chi=4,
vertex 0 critical, every generator's edge non-critical.

We enforce Skottova-Steiner Prop 5.1: min-degree >= 6, so connection set has >=6
non-identity elements (counting inverses). 6-regular Cayley graph: connection set
S = S^{-1}, |S| = 6, 0 not in S.
"""
import itertools
from critedge import chromatic_number
import networkx as nx


def cayley_abelian(dims, S):
    """Cayley graph of product of cyclic groups (dims=(a,b,...)) with connection
    set S (list of tuples). Vertices = all tuples; g~h iff g-h in S."""
    import itertools as it
    elems = list(it.product(*[range(d) for d in dims]))
    Sset = set(S)
    G = nx.Graph()
    G.add_nodes_from(elems)
    for g in elems:
        for s in S:
            h = tuple((gi + si) % di for gi, si, di in zip(g, s, dims))
            G.add_edge(g, h)
    return G


def neg(s, dims):
    return tuple((-si) % di for si, di in zip(s, dims))


def symmetric_connection_sets(dims, target_degree):
    """Yield symmetric (S=S^{-1}) connection sets of given degree (=|S|),
    0 not in S, generating the group (for connectivity)."""
    import itertools as it
    elems = [e for e in it.product(*[range(d) for d in dims])
             if any(e)]  # exclude identity
    # group elements into {s, -s} orbits
    seen = set()
    orbits = []
    for e in elems:
        if e in seen:
            continue
        ne = neg(e, dims)
        orbit = {e, ne}
        seen |= orbit
        orbits.append(sorted(orbit))
    # an involution {s} where s=-s contributes degree 1; a pair contributes 2.
    # choose orbits whose total size == target_degree
    n = 1
    for d in dims:
        n *= d
    for r in range(1, len(orbits) + 1):
        for combo in it.combinations(orbits, r):
            S = [x for orb in combo for x in orb]
            if len(S) != target_degree:
                continue
            # connectivity: subgroup generated by S is whole group
            if _generates(S, dims):
                yield S


def _generates(S, dims):
    import itertools as it
    elems = set(it.product(*[range(d) for d in dims]))
    gen = {tuple([0] * len(dims))}
    frontier = list(gen)
    Sset = list(S)
    while frontier:
        g = frontier.pop()
        for s in Sset:
            h = tuple((gi + si) % di for gi, si, di in zip(g, s, dims))
            if h not in gen:
                gen.add(h); frontier.append(h)
    return len(gen) == len(elems)


def analyze(dims, S):
    G = cayley_abelian(dims, S)
    if chromatic_number(G) != 4:
        return None
    # vertex 0 criticality (transitive)
    zero = tuple([0] * len(dims))
    H = G.copy(); H.remove_node(zero)
    if chromatic_number(H) >= 4:
        return None
    # per-generator-orbit edge criticality: check one edge from 0 along each s
    crit = 0
    checked_orbits = set()
    for s in S:
        ns = neg(s, dims)
        key = frozenset([s, ns])
        if key in checked_orbits:
            continue
        checked_orbits.add(key)
        h = s  # neighbor 0 + s
        He = G.copy()
        if He.has_edge(zero, h):
            He.remove_edge(zero, h)
            if chromatic_number(He) < 4:
                crit += 1
    return {"dims": dims, "S": S, "n": G.number_of_nodes(),
            "m": G.number_of_edges(), "num_crit_orbits": crit,
            "num_orbits": len(checked_orbits)}


def main():
    print("Cayley-graph (4,1)-witness search over NON-cyclic abelian groups")
    print("(circulants already closed; this is the next vertex-transitive family)")
    print("Prop 5.1: enforce degree >= 6.\n")
    # group orders 12..36, non-cyclic abelian decompositions with order >= 11
    group_dims = [
        (2, 6), (3, 4), (2, 8), (4, 4), (2, 2, 4), (2, 2, 5),
        (2, 10), (3, 6), (2, 12), (4, 6), (5, 5), (2, 2, 6),
        (3, 3, 3), (2, 2, 2, 3), (6, 6), (2, 18),
    ]
    best = None
    witnesses = []
    examined = 0
    for dims in group_dims:
        order = 1
        for d in dims: order *= d
        if order < 11:
            continue
        # try degrees 6 and 8
        for deg in (6, 8):
            count_here = 0
            for S in symmetric_connection_sets(dims, deg):
                res = analyze(dims, S)
                if res is None:
                    continue
                examined += 1
                count_here += 1
                nc = res["num_crit_orbits"]
                if best is None or nc < best["num_crit_orbits"]:
                    best = res
                if nc == 0:
                    witnesses.append(res)
                    print(f"  *** WITNESS Cayley({dims}) S={S} deg={deg} "
                          f"n={res['n']} ZERO critical edges ***")
            if count_here:
                bs = (f"best C({best['dims']}) {best['num_crit_orbits']}/"
                      f"{best['num_orbits']} crit-orbits" if best else "-")
                print(f"  group {dims} (order {order}), deg={deg}: "
                      f"{count_here} 4-vtx-critical Cayley graphs; {bs}")
    print("\n" + "=" * 60)
    print(f"4-vtx-critical Cayley graphs (non-cyclic abelian) examined: {examined}")
    if witnesses:
        print(f"WITNESSES: {len(witnesses)}")
        for w in witnesses:
            print(f"   Cayley({w['dims']}) S={w['S']} n={w['n']} m={w['m']}")
    else:
        print("NO non-cyclic-abelian Cayley (4,1)-witness in tested groups.")
        if best:
            print(f"Closest: Cayley({best['dims']}) S={best['S']} "
                  f"{best['num_crit_orbits']}/{best['num_orbits']} critical orbits "
                  f"(n={best['n']}, m={best['m']}).")
    print("=" * 60)


if __name__ == "__main__":
    main()
